"""initial schema

Revision ID: 0001
Revises:
Create Date: 2026-08-02 19:57:12.027670
"""

from collections.abc import Sequence

import sqlalchemy as sa

import app.models
from alembic import op

revision: str = "0001"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "application_settings",
        sa.Column("key", sa.String(length=120), nullable=False),
        sa.Column("value", sa.JSON(), nullable=False),
        sa.Column("updated_at", app.models.UTCDateTime(), nullable=False),
        sa.PrimaryKeyConstraint("key"),
    )
    op.create_table(
        "events",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("polymarket_id", sa.String(length=80), nullable=False),
        sa.Column("title", sa.Text(), nullable=False),
        sa.Column("original_rules", sa.Text(), nullable=False),
        sa.Column("resolution_source", sa.Text(), nullable=True),
        sa.Column("active", sa.Boolean(), nullable=False),
        sa.Column("closed", sa.Boolean(), nullable=False),
        sa.Column("start_time", app.models.UTCDateTime(), nullable=True),
        sa.Column("end_time", app.models.UTCDateTime(), nullable=True),
        sa.Column("raw_data", sa.JSON(), nullable=False),
        sa.Column("created_at", app.models.UTCDateTime(), nullable=False),
        sa.Column("updated_at", app.models.UTCDateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_events_active"), "events", ["active"], unique=False)
    op.create_index(op.f("ix_events_closed"), "events", ["closed"], unique=False)
    op.create_index(op.f("ix_events_end_time"), "events", ["end_time"], unique=False)
    op.create_index(op.f("ix_events_polymarket_id"), "events", ["polymarket_id"], unique=True)
    op.create_table(
        "provider_errors",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("provider", sa.String(length=80), nullable=False),
        sa.Column("operation", sa.String(length=120), nullable=False),
        sa.Column("error_type", sa.String(length=120), nullable=False),
        sa.Column("message", sa.Text(), nullable=False),
        sa.Column("details", sa.JSON(), nullable=False),
        sa.Column("retryable", sa.Boolean(), nullable=False),
        sa.Column("occurred_at", app.models.UTCDateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_provider_errors_provider_time",
        "provider_errors",
        ["provider", "occurred_at"],
        unique=False,
    )
    op.create_table(
        "markets",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("event_id", sa.Integer(), nullable=False),
        sa.Column("polymarket_id", sa.String(length=80), nullable=False),
        sa.Column("condition_id", sa.String(length=80), nullable=False),
        sa.Column("question", sa.Text(), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("resolution_source", sa.Text(), nullable=True),
        sa.Column("active", sa.Boolean(), nullable=False),
        sa.Column("closed", sa.Boolean(), nullable=False),
        sa.Column("close_time", app.models.UTCDateTime(), nullable=True),
        sa.Column("liquidity", sa.Numeric(precision=18, scale=8), nullable=True),
        sa.Column("minimum_order_size", sa.Numeric(precision=18, scale=8), nullable=True),
        sa.Column("raw_data", sa.JSON(), nullable=False),
        sa.Column("created_at", app.models.UTCDateTime(), nullable=False),
        sa.Column("updated_at", app.models.UTCDateTime(), nullable=False),
        sa.ForeignKeyConstraint(["event_id"], ["events.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("condition_id"),
    )
    op.create_index(op.f("ix_markets_active"), "markets", ["active"], unique=False)
    op.create_index(op.f("ix_markets_close_time"), "markets", ["close_time"], unique=False)
    op.create_index(op.f("ix_markets_closed"), "markets", ["closed"], unique=False)
    op.create_index(op.f("ix_markets_event_id"), "markets", ["event_id"], unique=False)
    op.create_index(op.f("ix_markets_polymarket_id"), "markets", ["polymarket_id"], unique=True)
    op.create_table(
        "forecast_runs",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("market_id", sa.Integer(), nullable=False),
        sa.Column("provider", sa.String(length=80), nullable=False),
        sa.Column("model", sa.String(length=80), nullable=False),
        sa.Column("initialization_time", app.models.UTCDateTime(), nullable=True),
        sa.Column("forecast_horizon_hours", sa.Integer(), nullable=True),
        sa.Column("retrieved_at", app.models.UTCDateTime(), nullable=False),
        sa.Column("status", sa.String(length=32), nullable=False),
        sa.Column("raw_metadata", sa.JSON(), nullable=False),
        sa.ForeignKeyConstraint(["market_id"], ["markets.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_forecast_runs_provider_retrieved",
        "forecast_runs",
        ["provider", "retrieved_at"],
        unique=False,
    )
    op.create_table(
        "normalized_rules",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("market_id", sa.Integer(), nullable=False),
        sa.Column("location_name", sa.String(length=160), nullable=False),
        sa.Column("latitude", sa.Float(), nullable=False),
        sa.Column("longitude", sa.Float(), nullable=False),
        sa.Column("station_id", sa.String(length=32), nullable=False),
        sa.Column("local_date", sa.Date(), nullable=False),
        sa.Column("timezone", sa.String(length=80), nullable=False),
        sa.Column("measurement", sa.String(length=80), nullable=False),
        sa.Column("unit", sa.String(length=24), nullable=False),
        sa.Column("resolution_source", sa.Text(), nullable=False),
        sa.Column("rounding_method", sa.String(length=32), nullable=False),
        sa.Column("reporting_period", sa.String(length=80), nullable=False),
        sa.Column("confidence_score", sa.Integer(), nullable=False),
        sa.Column("field_provenance", sa.JSON(), nullable=False),
        sa.Column("ambiguities", sa.JSON(), nullable=False),
        sa.Column("original_rules", sa.Text(), nullable=False),
        sa.Column("created_at", app.models.UTCDateTime(), nullable=False),
        sa.Column("updated_at", app.models.UTCDateTime(), nullable=False),
        sa.ForeignKeyConstraint(["market_id"], ["markets.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("market_id"),
    )
    op.create_index(
        op.f("ix_normalized_rules_local_date"), "normalized_rules", ["local_date"], unique=False
    )
    op.create_index(
        op.f("ix_normalized_rules_station_id"), "normalized_rules", ["station_id"], unique=False
    )
    op.create_table(
        "observations",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("market_id", sa.Integer(), nullable=True),
        sa.Column("station_id", sa.String(length=32), nullable=False),
        sa.Column("observed_at", app.models.UTCDateTime(), nullable=False),
        sa.Column("air_temperature", sa.Float(), nullable=True),
        sa.Column("precipitation", sa.Float(), nullable=True),
        sa.Column("source", sa.String(length=80), nullable=False),
        sa.Column("retrieved_at", app.models.UTCDateTime(), nullable=False),
        sa.Column("quality_flags", sa.JSON(), nullable=False),
        sa.Column("raw_data", sa.JSON(), nullable=False),
        sa.ForeignKeyConstraint(["market_id"], ["markets.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_observations_station_time", "observations", ["station_id", "observed_at"], unique=False
    )
    op.create_table(
        "outcomes",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("market_id", sa.Integer(), nullable=False),
        sa.Column("label", sa.String(length=120), nullable=False),
        sa.Column("token_id", sa.String(length=100), nullable=False),
        sa.Column("bucket_low", sa.Float(), nullable=True),
        sa.Column("bucket_high", sa.Float(), nullable=True),
        sa.Column("low_inclusive", sa.Boolean(), nullable=False),
        sa.Column("high_inclusive", sa.Boolean(), nullable=False),
        sa.Column("created_at", app.models.UTCDateTime(), nullable=False),
        sa.Column("updated_at", app.models.UTCDateTime(), nullable=False),
        sa.ForeignKeyConstraint(["market_id"], ["markets.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("market_id", "label"),
    )
    op.create_index(op.f("ix_outcomes_market_id"), "outcomes", ["market_id"], unique=False)
    op.create_index(op.f("ix_outcomes_token_id"), "outcomes", ["token_id"], unique=True)
    op.create_table(
        "probability_estimates",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("market_id", sa.Integer(), nullable=False),
        sa.Column("generated_at", app.models.UTCDateTime(), nullable=False),
        sa.Column("valid_members", sa.Integer(), nullable=False),
        sa.Column("excluded_members", sa.Integer(), nullable=False),
        sa.Column("outcome_probabilities", sa.JSON(), nullable=False),
        sa.Column("ensemble_spread", sa.Float(), nullable=False),
        sa.Column("uncertainty_score", sa.Float(), nullable=False),
        sa.Column("model_weights", sa.JSON(), nullable=False),
        sa.ForeignKeyConstraint(["market_id"], ["markets.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_probabilities_market_generated",
        "probability_estimates",
        ["market_id", "generated_at"],
        unique=False,
    )
    op.create_table(
        "rejected_signals",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("market_id", sa.Integer(), nullable=True),
        sa.Column("generated_at", app.models.UTCDateTime(), nullable=False),
        sa.Column("reasons", sa.JSON(), nullable=False),
        sa.Column("candidate_data", sa.JSON(), nullable=False),
        sa.ForeignKeyConstraint(["market_id"], ["markets.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_rejections_market_generated",
        "rejected_signals",
        ["market_id", "generated_at"],
        unique=False,
    )
    op.create_table(
        "forecast_members",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("forecast_run_id", sa.Integer(), nullable=False),
        sa.Column("member_id", sa.String(length=80), nullable=False),
        sa.Column("points", sa.JSON(), nullable=False),
        sa.Column("daily_value", sa.Float(), nullable=True),
        sa.Column("bias_correction", sa.Float(), nullable=False),
        sa.Column("valid", sa.Boolean(), nullable=False),
        sa.Column("exclusion_reason", sa.String(length=160), nullable=True),
        sa.ForeignKeyConstraint(["forecast_run_id"], ["forecast_runs.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("forecast_run_id", "member_id"),
    )
    op.create_index(
        op.f("ix_forecast_members_forecast_run_id"),
        "forecast_members",
        ["forecast_run_id"],
        unique=False,
    )
    op.create_table(
        "order_book_snapshots",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("market_id", sa.Integer(), nullable=False),
        sa.Column("outcome_id", sa.Integer(), nullable=False),
        sa.Column("captured_at", app.models.UTCDateTime(), nullable=False),
        sa.Column("bids", sa.JSON(), nullable=False),
        sa.Column("asks", sa.JSON(), nullable=False),
        sa.Column("best_bid", sa.Numeric(precision=18, scale=8), nullable=True),
        sa.Column("best_ask", sa.Numeric(precision=18, scale=8), nullable=True),
        sa.Column("spread", sa.Numeric(precision=18, scale=8), nullable=True),
        sa.Column("midpoint", sa.Numeric(precision=18, scale=8), nullable=True),
        sa.Column("available_depth", sa.Numeric(precision=18, scale=8), nullable=False),
        sa.Column("minimum_order_size", sa.Numeric(precision=18, scale=8), nullable=False),
        sa.Column("tick_size", sa.Numeric(precision=18, scale=8), nullable=False),
        sa.Column("raw_data", sa.JSON(), nullable=False),
        sa.ForeignKeyConstraint(["market_id"], ["markets.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["outcome_id"], ["outcomes.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_order_books_market_captured",
        "order_book_snapshots",
        ["market_id", "captured_at"],
        unique=False,
    )
    op.create_table(
        "signals",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("market_id", sa.Integer(), nullable=False),
        sa.Column("outcome_id", sa.Integer(), nullable=False),
        sa.Column("generated_at", app.models.UTCDateTime(), nullable=False),
        sa.Column("model_probability", sa.Numeric(precision=18, scale=8), nullable=False),
        sa.Column("executable_ask", sa.Numeric(precision=18, scale=8), nullable=False),
        sa.Column("raw_edge", sa.Numeric(precision=18, scale=8), nullable=False),
        sa.Column("usable_edge", sa.Numeric(precision=18, scale=8), nullable=False),
        sa.Column("buffers", sa.JSON(), nullable=False),
        sa.Column("fingerprint", sa.String(length=128), nullable=False),
        sa.Column("alerted_at", app.models.UTCDateTime(), nullable=True),
        sa.Column("alert_error", sa.Text(), nullable=True),
        sa.Column("signal_data", sa.JSON(), nullable=False),
        sa.ForeignKeyConstraint(["market_id"], ["markets.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["outcome_id"], ["outcomes.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_signals_fingerprint"), "signals", ["fingerprint"], unique=True)
    op.create_index(
        "ix_signals_market_generated", "signals", ["market_id", "generated_at"], unique=False
    )
    op.create_table(
        "paper_positions",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("signal_id", sa.Integer(), nullable=False),
        sa.Column("market_id", sa.Integer(), nullable=False),
        sa.Column("outcome_id", sa.Integer(), nullable=False),
        sa.Column("entered_at", app.models.UTCDateTime(), nullable=False),
        sa.Column("entry_price", sa.Numeric(precision=18, scale=8), nullable=False),
        sa.Column("amount", sa.Numeric(precision=18, scale=8), nullable=False),
        sa.Column("shares", sa.Numeric(precision=18, scale=8), nullable=False),
        sa.Column("fees", sa.Numeric(precision=18, scale=8), nullable=False),
        sa.Column("status", sa.String(length=24), nullable=False),
        sa.Column("signal_data", sa.JSON(), nullable=False),
        sa.ForeignKeyConstraint(
            ["market_id"],
            ["markets.id"],
        ),
        sa.ForeignKeyConstraint(
            ["outcome_id"],
            ["outcomes.id"],
        ),
        sa.ForeignKeyConstraint(
            ["signal_id"],
            ["signals.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("signal_id"),
    )
    op.create_index(
        op.f("ix_paper_positions_market_id"), "paper_positions", ["market_id"], unique=False
    )
    op.create_index("ix_paper_positions_status", "paper_positions", ["status"], unique=False)
    op.create_table(
        "paper_settlements",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("position_id", sa.Integer(), nullable=False),
        sa.Column("settled_at", app.models.UTCDateTime(), nullable=False),
        sa.Column("won", sa.Boolean(), nullable=False),
        sa.Column("payout", sa.Numeric(precision=18, scale=8), nullable=False),
        sa.Column("realized_pnl", sa.Numeric(precision=18, scale=8), nullable=False),
        sa.Column("brier_score", sa.Float(), nullable=False),
        sa.Column("resolution_data", sa.JSON(), nullable=False),
        sa.ForeignKeyConstraint(
            ["position_id"],
            ["paper_positions.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("position_id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("paper_settlements")
    op.drop_index("ix_paper_positions_status", table_name="paper_positions")
    op.drop_index(op.f("ix_paper_positions_market_id"), table_name="paper_positions")
    op.drop_table("paper_positions")
    op.drop_index("ix_signals_market_generated", table_name="signals")
    op.drop_index(op.f("ix_signals_fingerprint"), table_name="signals")
    op.drop_table("signals")
    op.drop_index("ix_order_books_market_captured", table_name="order_book_snapshots")
    op.drop_table("order_book_snapshots")
    op.drop_index(op.f("ix_forecast_members_forecast_run_id"), table_name="forecast_members")
    op.drop_table("forecast_members")
    op.drop_index("ix_rejections_market_generated", table_name="rejected_signals")
    op.drop_table("rejected_signals")
    op.drop_index("ix_probabilities_market_generated", table_name="probability_estimates")
    op.drop_table("probability_estimates")
    op.drop_index(op.f("ix_outcomes_token_id"), table_name="outcomes")
    op.drop_index(op.f("ix_outcomes_market_id"), table_name="outcomes")
    op.drop_table("outcomes")
    op.drop_index("ix_observations_station_time", table_name="observations")
    op.drop_table("observations")
    op.drop_index(op.f("ix_normalized_rules_station_id"), table_name="normalized_rules")
    op.drop_index(op.f("ix_normalized_rules_local_date"), table_name="normalized_rules")
    op.drop_table("normalized_rules")
    op.drop_index("ix_forecast_runs_provider_retrieved", table_name="forecast_runs")
    op.drop_table("forecast_runs")
    op.drop_index(op.f("ix_markets_polymarket_id"), table_name="markets")
    op.drop_index(op.f("ix_markets_event_id"), table_name="markets")
    op.drop_index(op.f("ix_markets_closed"), table_name="markets")
    op.drop_index(op.f("ix_markets_close_time"), table_name="markets")
    op.drop_index(op.f("ix_markets_active"), table_name="markets")
    op.drop_table("markets")
    op.drop_index("ix_provider_errors_provider_time", table_name="provider_errors")
    op.drop_table("provider_errors")
    op.drop_index(op.f("ix_events_polymarket_id"), table_name="events")
    op.drop_index(op.f("ix_events_end_time"), table_name="events")
    op.drop_index(op.f("ix_events_closed"), table_name="events")
    op.drop_index(op.f("ix_events_active"), table_name="events")
    op.drop_table("events")
    op.drop_table("application_settings")
    # ### end Alembic commands ###
